### ISSUE TITLE
asciitable.d(67,35): Error: template std.string.leftJustify cannot deduce function from argument 

### ISSUE THREAD

**Issue by truedat101** [gizmomogwai/ponies#1]
```
$ dub build
Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86.
colored 0.0.8: building configuration "library"...
androidlogger 0.0.3: building configuration "library"...
ponies 0.0.2: building configuration "application"...
source\asciitable.d(67,35): Error: template std.string.leftJustify cannot deduce function from argument types !()(string, ulong, char), candidates are:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\string.d(3630,3):        std.string.leftJustify(S)(S s, size_t width, dchar fillChar = ' ') if (isSomeString!S)
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

**Comment by gizmomogwai** [comment]
mh ... in the meantime i added an automated build that is green at the moment.
can you please give more informations?
dmd used and sha1 of the code?

thanks in advance, christian

**Comment by truedat101** [comment]
Apologies, details : 

ldc2 ldc2-07b7abef-windows-x64.7z

```
$ ldc2 --version
LDC - the LLVM D compiler (1.7.0git-07b7abe):
  based on DMD v2.077.1 and LLVM 5.0.1
  built with LDC - the LLVM D compiler (1.6.0)
  Default target: x86_64-pc-windows-msvc
  Host CPU: nehalem
  http://dlang.org - http://wiki.dlang.org/LDC

```

**Comment by gizmomogwai** [comment]
Thanks for the details. I do not have this problem with
    $ ldc2 --version
    LDC - the LLVM D compiler (1.7.0):
      based on DMD v2.077.1 and LLVM 5.0.1
      built with LDC - the LLVM D compiler (1.7.0)
      Default target: x86_64-apple-darwin17.3.0
      Host CPU: haswell
      http://dlang.org - http://wiki.dlang.org/LDC

I am trying to add ldc to the travis build first ...

**Comment by truedat101** [comment]
Hmm, using ConEmu bash shell.

**Comment by gizmomogwai** [comment]
Is this still an issue for you?

**Comment by truedat101** [comment]
I'll have to retry.  Will get back to you today.  I am on Windows which may present some issue, given that it is not a true POSIX environment.

**Comment by truedat101** [comment]
Well I see the problem.  I wish I could read better.  Note: C:\D\dmd2\windows\bin\

DMD is being selected, not ldc2.  So I suppose this isn't compatible with DMD.

**Comment by gizmomogwai** [comment]
mhh .. should also be compatible with dmd ... the travis build includes ldc and dmd.
is it still the same compile error?
i think there are new versions of dmd and ldc released!

**Comment by truedat101** [comment]
Let me post my dmd version, probably quite old.

**Comment by truedat101** [comment]
ldc2 builds fine.

**Comment by truedat101** [comment]
$ dmd --version
DMD32 D Compiler v2.078.1

Copyright (c) 1999-2017 by The D Language Foundation written by Walter Bright

**Comment by gizmomogwai** [comment]
mhh ..the most current one is 2.079.1 ... btw. dconf is starting tomorrow .. will you be there?

**Comment by truedat101** [comment]
Hmm, no didn't make it out there.  You are in Germany I guess??   I will plan for a talk next year on blockchain I hope.  Please look for Ali Cehreli (http://ddili.org/ders/d.en/index.html) , book author, as I think he will be presenting.  We run the dlang meetup here in the SF Bay area.

**Comment by truedat101** [comment]
Will you be presenting at dconf?

**Comment by gizmomogwai** [comment]
Yes ... will be there ... Ali is a very nice guy!

**Comment by gizmomogwai** [comment]
So I think this is now resolved for you? should just work ....
otherwise please post the compile error :)

**Comment by truedat101** [comment]
Well resolved if I use ldc, but compile error still (in original post) for dmd.

**Comment by gizmomogwai** [comment]
i resolved this compile error in asciitable. should work with the newest version.
